export const PROJECT_VERSION = "0.1.0";
export const STATE_SCHEMA_VERSION = 6;
export const PROJECT_PHASE = "Fase 1 completada";
export const CAPABILITY_IMPLEMENTED = "IMPLEMENTADA";
export const SPECIFIED_NOT_IMPLEMENTED = "ESPECIFICADA — NO IMPLEMENTADA";
